
const letters=["أ","ب","ج","د"];
const views={home:document.getElementById("homeView"),quiz:document.getElementById("quizView"),result:document.getElementById("resultView")};
let lecture=null,index=0,score=0,answered=false;
function showView(name){Object.values(views).forEach(v=>v.classList.remove("active"));views[name].classList.add("active");window.scrollTo({top:0,behavior:"smooth"});}
function buildHome(){const grid=document.getElementById("lectureGrid");grid.innerHTML="";QUIZ_DATA.forEach((l,i)=>{const card=document.createElement("button");card.className="lecture-card";card.innerHTML=`<span class="lecture-no">${i+1}</span><h3>${l.title}</h3><p>${l.count} سؤال اختيار من متعدد</p><span class="start"><span>ابدأ الاختبار</span><span>←</span></span>`;card.onclick=()=>startLecture(l.id);grid.appendChild(card);});}
function startLecture(id){lecture=QUIZ_DATA.find(l=>l.id===id);index=0;score=0;answered=false;document.getElementById("lectureTitle").textContent=lecture.title;showView("quiz");renderQuestion();}
function renderQuestion(){answered=false;const q=lecture.questions[index];document.getElementById("progressText").textContent=`السؤال ${index+1} من ${lecture.count}`;document.getElementById("questionNumber").textContent=`السؤال رقم ${q.number}`;document.getElementById("scoreText").textContent=`النتيجة: ${score}`;document.getElementById("progressBar").style.width=`${((index+1)/lecture.count)*100}%`;const img=document.getElementById("questionImage");img.src=q.image;img.alt=`السؤال ${q.number}`;const box=document.getElementById("answerButtons");box.innerHTML="";letters.forEach(letter=>{const b=document.createElement("button");b.className="answer-btn";b.textContent=letter;b.onclick=()=>chooseAnswer(letter,b);box.appendChild(b);});const feedback=document.getElementById("feedback");feedback.className="feedback";feedback.textContent="";const next=document.getElementById("nextBtn");next.disabled=true;next.textContent=index===lecture.count-1?"عرض النتيجة":"السؤال التالي";}
function chooseAnswer(letter,button){if(answered)return;answered=true;const q=lecture.questions[index];const buttons=[...document.querySelectorAll(".answer-btn")];buttons.forEach(b=>b.disabled=true);const correct=buttons.find(b=>b.textContent===q.answer);correct.classList.add("correct");const feedback=document.getElementById("feedback");if(letter===q.answer){score++;button.classList.add("correct");feedback.className="feedback show good";feedback.textContent="✅ إجابتك صحيحة";}else{button.classList.add("wrong");feedback.className="feedback show bad";feedback.textContent=`❌ إجابتك خاطئة — الخيار الصحيح هو (${q.answer})`; }document.getElementById("scoreText").textContent=`النتيجة: ${score}`;document.getElementById("nextBtn").disabled=false;}
function nextQuestion(){if(!answered)return;if(index<lecture.count-1){index++;renderQuestion();window.scrollTo({top:0,behavior:"smooth"});}else showResult();}
function showResult(){document.getElementById("resultLecture").textContent=lecture.title;document.getElementById("resultScore").textContent=`${score} / ${lecture.count}`;const pct=Math.round(score/lecture.count*100);document.getElementById("resultMessage").textContent=pct>=90?"ممتاز جداً! إتقان قوي للمحاضرة.":pct>=70?"نتيجة جيدة، راجع الأسئلة التي أخطأت بها.":pct>=50?"جيد كبداية، أعد الاختبار لتثبيت المعلومات.":"تحتاج إلى مراجعة المحاضرة ثم إعادة التدريب.";showView("result");}
document.getElementById("nextBtn").onclick=nextQuestion;document.getElementById("backBtn").onclick=()=>showView("home");document.getElementById("homeBtn").onclick=()=>showView("home");document.getElementById("restartBtn").onclick=()=>startLecture(lecture.id);buildHome();
